-- Inicializamos la BD
INSERT INTO Tea (idtea, tea, estado) VALUES (1, '99.90%',1);
INSERT INTO Tea (idtea, tea, estado) VALUES (2,'95.90%',1);
INSERT INTO Tea (idtea, tea, estado) VALUES (3,'90.90%',1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (1,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (2,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (3,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (4,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (5,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (6,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (7,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (8,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (9,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (10,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (11,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (12,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (13,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (14,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (15,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (16,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (17,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (18,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (19,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (20,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (21,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (22,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (23,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (24,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (25,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (26,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (27,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (28,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (29,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (30,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (31,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (32,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (33,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (34,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (35,1);
INSERT INTO Cuotas (idcuotas, estado) VALUES (36,1);
INSERT INTO Dias (iddias, dia, estado) VALUES (1, 5,1);
INSERT INTO Dias (iddias, dia, estado) VALUES (2, 20,1);
INSERT INTO Cliente (idcliente, dni, nombre,apellidos,estado) VALUES (1, 45664829,'Gustavo','Osorio',1);
INSERT INTO Cliente (idcliente, dni, nombre,apellidos,estado) VALUES (2, 45664820,'Pedro','Gomez',1);
INSERT INTO Cliente (idcliente, dni, nombre,apellidos,estado) VALUES (3, 45664822,'Carmen','Sosa',1);
INSERT INTO Tarjeta (idtarjeta, idcliente, tarjeta,numtarjeta,estado) VALUES (1, 3,'CLASICA','12345678123456',1);
INSERT INTO Tarjeta (idtarjeta, idcliente, tarjeta,numtarjeta,estado) VALUES (2, 2,'ORO','12345678123457',1);
INSERT INTO Tarjeta (idtarjeta, idcliente, tarjeta,numtarjeta,estado) VALUES (3, 1,'BACK','12345678123458',1);
